name: Test

on:
  - push
  - pull_request

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Test in Docker
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2
      - name: Build a Docker Image
        run: docker image build -t oduwsdl/wsdlthesis .
      - name: Run make in a Container for Testing
        run: docker container run --name=wsdlthesis oduwsdl/wsdlthesis
      - name: Copy PDF Out from the Container
        run: docker container cp wsdlthesis:/src/main.pdf ./
      - name: Upload Generated PDF
        uses: actions/upload-artifact@v2
        with:
          path: main.pdf
